ETAB
2734	01.09.2009	PROD	HLIQ  HWEF    BHPT 1 
2734	13.09.2012	INJE	HWAT  HWEF    BHPT 250 
2734_CT	01.10.2012	INJE	HWAT  HWEF    BHPT 250 
--********************--
2443	01.05.2013	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2770	01.09.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
120RTM	01.08.1989	PROD	HOIL  HWEF    BHPT 1 
--********************--
2733	01.10.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2740	01.07.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2244	01.04.2010	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2263	01.06.2009	PROD	HLIQ  HWEF    BHPT 1 
2263	01.12.2012	INJE	HWAT  HWEF    BHPT 250 
--********************--
2240	01.01.2010	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2241	01.07.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2264	01.03.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2265	01.03.2009	PROD	HLIQ  HWEF    BHPT 1 
2265	12.05.2011	INJE	HWAT  HWEF    BHPT 220 
2265_CT	01.11.2011	INJE	HWAT  HWEF    BHPT 250 
--********************--
2604	01.03.2010	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2605	01.01.2010	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2466	01.01.2002	PROD	HLIQ  HWEF    BHPT 1 
2466	03.09.2013	INJE	HWAT  HWEF    BHPT 250 
--********************--
2607	01.12.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2446	01.08.2000	PROD	HLIQ  HWEF    BHPT 1 
2446	12.05.2010	INJE	HWAT  HWEF    BHPT 250 
--********************--
2602	01.06.2010	PROD	HLIQ  HWEF    BHPT 1 
2602	08.09.2012	INJE	HWAT  HWEF    BHPT 250 
2602_CT	01.09.2012	INJE	HWAT  HWEF    BHPT 250 
--********************--
2603	01.08.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2468	01.07.2003	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2726	01.11.2009	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2518	01.06.2008	PROD	HLIQ  HWEF    BHPT 1 
--2518	01.05.2013	PROD	HOIL  HWEF    BHPT 1 -- предположительно порван СТ
--********************--
2516	01.07.2008	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2517	01.04.2008	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2445	01.06.2013	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2512G	01.05.2014	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2514G	01.07.2014	PROD	HLIQ  HWEF    BHPT 1 
--********************--
2511G	01.09.2014	PROD	HLIQ  HWEF    BHPT 1 
ENDE
